### PR TITLE
feat: added Image and Input components

### PR DESCRIPTION
**Pull request by AnjaliDeshwani**
- Image Component
  -image.html
  -image.css

- Input Component
  -input.html
  -input.css

### CODE REVIEW

**Review by Pratik1005 — APPROVED** [review]
You can use type password for password fields, just a suggestion.

**Comment by AnjaliDeshwani** [comment]
> You can use type password for password fields, just a suggestion.

Thanks, good catch. I will update it.

**Review by JowelTisso — APPROVED** [review]
Looks Good.
Suggestion: You can set the dimensions of the components as it would be in a real scenario.

**Comment by AnjaliDeshwani** [comment]
> Looks Good. Suggestion: You can set the dimensions of the components as it would be in a real scenario.

Thanks Jowel for reviewing.  Could you please highlight or explain it more what dimensions you are referring.

**Comment by JowelTisso** [comment]
The dimension as in the width of alert and width of input elements, they are too long for a real scenario. And the floating action button is mostly circle with an action icon in it. So you can practice with real width in your documentation.

**Comment by AnjaliDeshwani** [comment]
> The dimension as in the width of alert and width of input elements, they are too long for a real scenario. And the floating action button is mostly circle with an action icon in it. So you can practice with real width in your documentation.

Right Jowel, I understood your point now. Actually these alert and input elements are set as 100% width which will be respective to its parent. 
I will make theses required changes once done with components.

**Pull request merged**
